/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

/**
 *
 * @author Bishal
 */
import Project1.ConnectionProvider;
import java.awt.BorderLayout;
import java.awt.*;
import static java.awt.BorderLayout.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

public class AutoGeneratedLectureNotesStudent implements ActionListener {
    private String courseID=IndividualCoursePageStudent.courseID;
    public static String clickedButton="";
    private JButton closeButton;
    private JFrame frame = new JFrame("Lecture Notes");

    // Make JPanels
    private JPanel panelLabel = new JPanel(new BorderLayout());
    private JPanel buttonGrid = new JPanel(new GridLayout(0, 1,10,10));//3,3 is hgap and vGap
    //private JPanel bottomPanel = new JPanel();

    // JLabel
    private JLabel label1 = new JLabel("List of All availabe Lecture Notes");
  
    private Set<String> LectureNotesAL= new HashSet<String>();
    private ArrayList<String> studentIDAL = new ArrayList<String>();
    private String teacherID= IndividualCoursePageStudent.teacherID;

    public AutoGeneratedLectureNotesStudent() {
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setPreferredSize(new Dimension(750,550));
        frame.setLocation(450,150);
        frame.add(createMainPanel());
        frame.setUndecorated(true);
        frame.pack();
        //frame.setLocationByPlatform(true);
        frame.setVisible(true);
         //JOptionPane.showMessageDialog(null, teacherID+" "+courseID);
    }
    
    public void accessPowerPointsFromTable()
    {
        try
        {
            String studentId= studentIDAL.get(0);
            //int id=Integer.parseInt(studentId);
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select powerpoints.assignmentName from powerpoints where teacherID =\"" + teacherID+ "\" and courseID=\""+courseID+"\"");
            while(rs.next())
            {
                LectureNotesAL.add(rs.getString(1));
            }
            //JOptionPane.showMessageDialog(null, studentId);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void accessStudentID()
    {
        try
        {
            //String username=Registration.txtUser;
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select studentID from student1 where username=\"" + Registration.txtUser.getText() + "\"and password1=\"" + Registration.txtPassword.getText() + "\"");
            while(rs.next())
            {
                studentIDAL.add(rs.getString(1));
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    private JPanel createMainPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        label1.setFont(new Font("Verdana",Font.PLAIN,30));

        
        panelLabel.add(label1,BorderLayout.CENTER);
        panelLabel.setBackground(Color.cyan);
        closeButton =new JButton("Close");
        closeButton.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           frame.setVisible(false);
           
         }
      });
        
        panelLabel.add(closeButton,BorderLayout.EAST);
        panel.add(panelLabel, BorderLayout.NORTH);
        accessStudentID();
        accessPowerPointsFromTable();
        
        if(LectureNotesAL.size()==0)
        {
            JOptionPane.showMessageDialog(null,"You Don't have any assignment Assigned Yet.");
        }
        // add Buttons
        Iterator iterOnAL= LectureNotesAL.iterator();
        while(iterOnAL.hasNext())
        {
            JButton button = new JButton(iterOnAL.next().toString());
            button.setPreferredSize(new Dimension(40,40));
            button.addActionListener(this);
            button.setBackground(Color.GREEN);
            button.setFont(new Font("Verdana",Font.PLAIN,30));
            buttonGrid.add(button);
            buttonGrid.setBackground(Color.WHITE);
        }
        panel.add(buttonGrid, BorderLayout.CENTER);

        // Add JText Area to bottom JPanel
        String num = "value";
        

        return panel;
    }

    public static void main(String args[]) {
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                new AutoGeneratedLectureNotesStudent();
            }
        };
        SwingUtilities.invokeLater(runnable);
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        JButton button = (JButton) e.getSource();
        clickedButton=button.getText();
        frame.setVisible(false);
        new PowerPointsAccessStudent().setVisible(true);
    }       
}