/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import Project1.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Bishal
 */
public class ContentPageStudentCourse extends javax.swing.JFrame {

    /**
     * Creates new form ContentPageTeacherCourse
     */
    public ContentPageStudentCourse() {
        initComponents();
        //getDetails();
    }
    //String uniqueID="";
    public void getDetails()
    {
        try
        {
            String name="";
            String uniqueID="";
            
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
           // String qrry = "select * from logindetails where username=\"" + Registration.textUser + "\"and password=\"" + Registration.txtPassword + "\"";
           ResultSet rs;
           rs = st.executeQuery("select *from student1 where username=\"" + Registration.txtUser.getText() + "\" and password1=\"" + Registration.txtPassword.getText() +"\"");
            // ResultSet rs = st.executeQuery("select *from logindetails");
            while(rs.next())
            {
                name+=rs.getString(3);
                uniqueID+=rs.getString(6);
            }
            // JOptionPane.showMessageDialog(null, uniqueID);
            lblCourseID.setText(name);
            lblStudentID.setText(uniqueID);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSyllabus = new javax.swing.JButton();
        btnLectureNotes = new javax.swing.JButton();
        btnAssignment1 = new javax.swing.JButton();
        btnAssignment2 = new javax.swing.JButton();
        btnAssignment3 = new javax.swing.JButton();
        btnExam1 = new javax.swing.JButton();
        btnExam2 = new javax.swing.JButton();
        btnExam3 = new javax.swing.JButton();
        lblStudentID = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/Close all jframe.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Content");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, -1, -1));

        btnSyllabus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSyllabus.setText("Course Syllabus");
        getContentPane().add(btnSyllabus, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 130, -1, 45));

        btnLectureNotes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLectureNotes.setText("Lecture Notes");
        getContentPane().add(btnLectureNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 243, 175, 45));

        btnAssignment1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssignment1.setText("Assignment1");
        btnAssignment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignment1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAssignment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 343, 175, 42));

        btnAssignment2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssignment2.setText("Assignment2");
        getContentPane().add(btnAssignment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 129, 172, 46));

        btnAssignment3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssignment3.setText("Assignment3");
        getContentPane().add(btnAssignment3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 343, 172, 44));

        btnExam1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExam1.setText("Exam1");
        btnExam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExam1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 446, 175, 43));

        btnExam2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExam2.setText("Exam2");
        getContentPane().add(btnExam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 246, 172, 42));

        btnExam3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExam3.setText("Exam3");
        getContentPane().add(btnExam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 446, 172, 42));

        lblStudentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStudentID.setText("GetStudentID");
        getContentPane().add(lblStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 66, -1, -1));

        lblCourseID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCourseID.setText("GetCourseID");
        getContentPane().add(lblCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 66, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/pages background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 700, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignment1ActionPerformed
        getDetails();
        new StartAssignment1Page().setVisible(true);
    }//GEN-LAST:event_btnAssignment1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExam1ActionPerformed
        // TODO add your handling code here:
        new StartExam1Page().setVisible(true);
    }//GEN-LAST:event_btnExam1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContentPageStudentCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContentPageStudentCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContentPageStudentCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContentPageStudentCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContentPageStudentCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignment1;
    private javax.swing.JButton btnAssignment2;
    private javax.swing.JButton btnAssignment3;
    private javax.swing.JButton btnExam1;
    private javax.swing.JButton btnExam2;
    private javax.swing.JButton btnExam3;
    private javax.swing.JButton btnLectureNotes;
    private javax.swing.JButton btnSyllabus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel lblCourseID;
    public static javax.swing.JLabel lblStudentID;
    // End of variables declaration//GEN-END:variables
}
