/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

/**
 *
 * @author Bishal
 */
public class courseContentPageTeacher extends javax.swing.JFrame {

    /**
     * Creates new form courseContentPageTeacher
     */
    public courseContentPageTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSyllabus = new javax.swing.JButton();
        btnLectureNotes = new javax.swing.JButton();
        btnAssignments = new javax.swing.JButton();
        btnExams = new javax.swing.JButton();
        btnNewAssignments = new javax.swing.JButton();
        btnNewExams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/Close all jframe.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Contents:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnSyllabus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSyllabus.setText("Course Syllabus");
        btnSyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyllabusActionPerformed(evt);
            }
        });
        getContentPane().add(btnSyllabus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 460, 45));

        btnLectureNotes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLectureNotes.setText("Lecture Notes");
        btnLectureNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLectureNotesActionPerformed(evt);
            }
        });
        getContentPane().add(btnLectureNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 460, 45));

        btnAssignments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssignments.setText("All Assignments");
        btnAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAssignments, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 460, 45));

        btnExams.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExams.setText("All Exams");
        btnExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamsActionPerformed(evt);
            }
        });
        getContentPane().add(btnExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 460, 45));

        btnNewAssignments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewAssignments.setText("Create New Assignments");
        btnNewAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAssignmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewAssignments, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 460, 45));

        btnNewExams.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewExams.setText("Create New Exams");
        btnNewExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewExamsActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 450, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAssignmentsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AssignmentPageTeacher().setVisible(true);
        
    }//GEN-LAST:event_btnNewAssignmentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AutoGeneratedAssignmentButtonTeacher();
    }//GEN-LAST:event_btnAssignmentsActionPerformed

    private void btnExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamsActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new AutoGeneratedExamButtonTeacher();
    }//GEN-LAST:event_btnExamsActionPerformed

    private void btnSyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyllabusActionPerformed
         setVisible(false);
        new SyallabusUploadTeacher().setVisible(true);
    }//GEN-LAST:event_btnSyllabusActionPerformed

    private void btnLectureNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLectureNotesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PowerPointsUploadTeacher22().setVisible(true);
    }//GEN-LAST:event_btnLectureNotesActionPerformed

    private void btnNewExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewExamsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new ExamsPageTeacher().setVisible(true);
    }//GEN-LAST:event_btnNewExamsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseContentPageTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseContentPageTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseContentPageTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseContentPageTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courseContentPageTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignments;
    private javax.swing.JButton btnExams;
    private javax.swing.JButton btnLectureNotes;
    private javax.swing.JButton btnNewAssignments;
    private javax.swing.JButton btnNewExams;
    private javax.swing.JButton btnSyllabus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
