/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import Project1.ConnectionProvider;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Bishal
 */
public class createNewAssignmentTeacher extends javax.swing.JFrame {

    /**
     * Creates new form createNewAssignmentTeacher
     */
    private String ExamInfo;
    public createNewAssignmentTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnChooseFile = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblCourseID = new javax.swing.JTextField();
        lblTeacherID = new javax.swing.JTextField();
        lblExamName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/Close all jframe.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Course ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Exam Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Teacher ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 174, -1, -1));

        btnChooseFile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnChooseFile.setText("Choose a File");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnChooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSave.setText("Save Exam");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        lblCourseID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(lblCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 97, 140, -1));

        lblTeacherID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(lblTeacherID, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 176, 140, -1));

        lblExamName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(lblExamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 262, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try
        {
            Connection con = ConnectionProvider.getCon();
            //String courseID=ContentPageTeacherCourse.lblCourseID.getText();
            //tring teacherID=ContentPageTeacherCourse.lblTeacherID.getText();

            String courseID=lblCourseID.getText();
            String teacherID=lblTeacherID.getText();
            String examName=lblExamName.getText();
            String file=ExamInfo;
            
            
            //String classroom=txtInstName.getText();
            
            PreparedStatement ps = con.prepareStatement("insert into assignment (courseID,teacherID,assignmentName,question)values(?,?,?,?)");
            //ps.setString(1,teacherName);
            ps.setString(1,courseID);
            ps.setString(2,teacherID);
            ps.setString(3,examName);
            ps.setString(4,file);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Sucessfully updated");
            
           
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        
        JFileChooser fileChooser= new JFileChooser();
        
        fileChooser.setCurrentDirectory(new File("."));
       // int response = fileChooser.showOpenDialog(null); //select file to open
        int response = fileChooser.showSaveDialog(null); //select file to save
        if(response ==JFileChooser.APPROVE_OPTION)
        {
            try {
                File inputFile = new File(fileChooser.getSelectedFile().getAbsolutePath());
                //JOptionPane.showMessageDialog(null,inputFile);
                Scanner inputReader= new Scanner(inputFile);
                //String fileInfo;
                while(inputReader.hasNext())
                {
                    ExamInfo=inputReader.nextLine();
                }
                
                JOptionPane.showMessageDialog(null,inputFile);
                lblExamName.setText(inputFile.toString());
            }
            catch (FileNotFoundException ex)
            {
                Logger.getLogger(createNewAssignmentTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createNewAssignmentTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createNewAssignmentTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createNewAssignmentTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createNewAssignmentTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createNewAssignmentTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lblCourseID;
    private javax.swing.JTextField lblExamName;
    private javax.swing.JTextField lblTeacherID;
    // End of variables declaration//GEN-END:variables
}
