/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import Project1.ConnectionProvider;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bishal
 */
public class PowerPointsAccessStudent extends javax.swing.JFrame {

    /**
     * Creates new form SyallabusUploadTeacher
     */
   // private String uniqueID=IndividualCoursePageTeacher.teacherID;
    private String teacherID=IndividualCoursePageStudent.teacherID;
    private String courseID=IndividualCoursePageStudent.courseID;
    private String studentID=IndividualCoursePageStudent.studentID;
    String fileIMG = null;
    byte[] img = null;
    String fileTXT = null;
    byte[] txt = null;
    public PowerPointsAccessStudent() {
        initComponents();
       //show_upload();
       accessPowerPointsFromTable();
       lblCourseName.setText(courseID);
      // getFile();
    }

   
    
     public void accessPowerPointsFromTable()
    {
         try
        {
            //String studentId= studentIDAL.get(0);
            //int id=Integer.parseInt(studentId);
            String file="";
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
         //   SELECT txtfile FROM learningmanagementsystem.powerpoints;
            ResultSet rs = st.executeQuery("select powerpoints.txtfile from powerpoints where teacherID =\"" + teacherID+ "\" and courseID=\""+courseID+"\""
                    + " and assignmentName =\"" + AutoGeneratedLectureNotesStudent.clickedButton+ "\"");
            while(rs.next())
            {
                file=rs.getString(1);
            }
            //JOptionPane.showMessageDialog(null, studentId);
          //  InputStream inputStream= new FileInputStream(new File(file));
          File file1= new File("file");
              Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + file +"");
              //file1.close();
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
  /*  public void show_upload() {
        ArrayList<Upload> list = UploadList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            /*
            row[2] = list.get(i).getAssignmentName(); 
            row[0] = list.get(i).getCourseID();
            row[1] = list.get(i).getCourseName();
             */
           /* row[0] = list.get(i).getID();
            //row[1]=list.get(i).getCourseID();
            row[1] = list.get(i).getAssignmentName();
            model.addRow(row);
        }
    }*/
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldPowerPoints = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/Close all jframe.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PowerPoints of");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 21, -1, -1));

        image.setText("i");
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 626, 17, -1));

        lblCourseName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCourseName.setText("GetCourseName");
        getContentPane().add(lblCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        fieldPowerPoints.setColumns(20);
        fieldPowerPoints.setRows(5);
        jScrollPane1.setViewportView(fieldPowerPoints);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 1070, 570));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

   
   private void btnTXTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Nothing");
    }                                                                                                                    

   /*private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                                   
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();

        byte[] Pic = (UploadList().get(i).getPic());
        
        if(Pic != null){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(Pic).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH));
            image.setIcon(imageIcon);
        }
        else{
            image.setIcon(null);
        }
        
        byte[] Txt = (UploadList().get(i).getTxt());
        if(Txt != null){
            String s = new String(Txt);
            fieldPowerPoints.setText(s);
        }
        else{
            fieldPowerPoints.setText("");
        }
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerPointsAccessStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerPointsAccessStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerPointsAccessStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerPointsAccessStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerPointsAccessStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea fieldPowerPoints;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName;
    // End of variables declaration//GEN-END:variables
}
