
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bishal
 */
public class Registration extends javax.swing.JFrame {

    
    /**
     * Creates new form Registration
     */
    // private javax.swing.JTextField txtName;
    int lastUniqueID;
    int lastUniqueIDTeach;
    public void setTxtName(JTextField txtName) 
    {
        this.txtName = txtName;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public Registration() {

       initComponents();
      // getLastUniqueIDStudent();
      // getLastUniqueIDTeacher();
       

    }
   
    public void getLastUniqueIDStudent()
    {
        if(comboType.getSelectedItem().equals("Student"))
        {
            try
            {
                Class.forName("java.sql.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
                Statement stmnt = conn.createStatement();
                String sql= "Select max(studentID) from student1";
                ResultSet rs= stmnt.executeQuery(sql);
                rs.next();
                
                lastUniqueID=Integer.parseInt(rs.getString("Max(studentID)"));
                //lastUniqueID=rs.getInt(1);
                if(rs.getString("Max(studentID)") == null)
                {
                    txtUniqueID.setText("1000");
                }
                else
                {
                    lastUniqueID++;
                    txtUniqueID.setText(Integer.toString(lastUniqueID));
                }
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }
    
     public void getLastUniqueIDTeacher()
    {
        
        if(comboType.getSelectedItem().equals("Teacher"))
        {
            try
            {
                Class.forName("java.sql.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
                Statement stmnt = conn.createStatement();
                String sql= "Select max(teacherID) from teacher";
                ResultSet rs= stmnt.executeQuery(sql);
                rs.next();
                
                lastUniqueIDTeach =Integer.parseInt(rs.getString("Max(teacherID)"));
                //lastUniqueID=rs.getInt(1);
                if(rs.getString("Max(teacherID)") == null)
                {
                    txtUniqueID.setText("100");
                }
                else
                {
                    lastUniqueIDTeach++;
                    txtUniqueID.setText(Integer.toString(lastUniqueIDTeach));
                }
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lbluserType = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        lblUniqueID = new javax.swing.JLabel();
        txtUniqueID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMain.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblMain.setText("Register");
        jPanel1.add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 130, 42));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUser.setText("UserName");
        lblUser.setAlignmentX(0.5F);
        lblUser.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, 33));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPassword.setText("Password");
        lblPassword.setAlignmentX(0.5F);
        lblPassword.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 110, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Name");
        lblName.setAlignmentX(0.5F);
        lblName.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 58, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setAlignmentX(0.5F);
        lblEmail.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 58, 34));

        lbluserType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbluserType.setText("User Type");
        lbluserType.setAlignmentX(0.5F);
        lbluserType.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lbluserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 110, 33));

        txtUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUser.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 320, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassword.setMaximumSize(new java.awt.Dimension(0, 0));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 206, 320, 40));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.setMaximumSize(new java.awt.Dimension(0, 0));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 336, 320, 40));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEmail.setMaximumSize(new java.awt.Dimension(0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 320, 40));

        txtPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPhone.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 463, 320, 40));

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, -1, 50));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setText("Already Have an acount");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, 50));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 110, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Canvas Login System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 260, 50));

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPhone.setText("Phone");
        lblPhone.setAlignmentX(0.5F);
        lblPhone.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 58, 33));

        comboType.setBackground(new java.awt.Color(204, 255, 255));
        comboType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Student", "Teacher" }));
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });
        jPanel1.add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 320, 40));

        lblUniqueID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUniqueID.setText("Unique ID");
        jPanel1.add(lblUniqueID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        txtUniqueID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUniqueID.setEnabled(false);
        jPanel1.add(txtUniqueID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if (lblMain.getText().equals("Register")) {
            if (comboType.getSelectedItem().toString().equals("Student")) 
            {
                if (txtUser.getText().length() > 0 && txtPassword.getText().length() > 0 && txtName.getText().length() > 0
                        && txtEmail.getText().length() > 0 && txtPhone.getText().length() > 0 && txtUniqueID.getText().length() > 0) 
                {
                    int studentId = Integer.parseInt(txtUniqueID.getText());
                    if (studentId >= 1000 && studentId <= 2000) 
                    {
                        String email = txtEmail.getText();
                        if (email.contains("@toromail.csudh.edu"))
                        {
                            if (txtPassword.getText().length() >= 6) 
                            {
                                if (txtPhone.getText().length() == 10) 
                                {
                                    RegisterCall(txtUser.getText(), txtPassword.getText(), txtName.getText(), txtEmail.getText(), txtPhone.getText(), txtUniqueID.getText());
                                    getLastUniqueIDStudent();
                                    LoginCall(txtUser.getText(), txtPassword.getText());

                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Please Enter a 10 digit Valid phone number");
                                }
                            } 
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Please Enter strong password of length greater than 6");
                            }

                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Please put the valid Email that you got from university");
                        }

                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Please put the valid ID that you got from university");
                    }

                } 
                else 
                {

                    JOptionPane.showMessageDialog(null, "Please fill in All the details");
                }
            }
            else if (comboType.getSelectedItem().toString().equals("Teacher"))
            {
                if (txtUser.getText().length() > 0 && txtPassword.getText().length() > 0 && txtName.getText().length() > 0
                        && txtEmail.getText().length() > 0 && txtPhone.getText().length() > 0 && txtUniqueID.getText().length() > 0) 
                {
                    int teacherId = Integer.parseInt(txtUniqueID.getText());
                    if (teacherId >= 100 && teacherId <= 200) 
                    {
                        String email = txtEmail.getText();
                        if (email.contains("csudh.edu"))
                        {
                            if (txtPassword.getText().length() >= 6) 
                            {
                                if (txtPhone.getText().length() == 10) 
                                {
                                    RegisterCallTeacher(txtUser.getText(), txtPassword.getText(), txtName.getText(), txtEmail.getText(), txtPhone.getText(), txtUniqueID.getText());
                                    getLastUniqueIDTeacher();
                                    LoginCallTeacher(txtUser.getText(), txtPassword.getText());

                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Please Enter a 10 digit Valid phone number");
                                }
                            } 
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Please Enter strong password of length greater than 6");
                            }

                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Please put the valid Email that you got from university");
                        }

                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Please put the valid ID that you got from university");
                    }

                } 
                else 
                {

                    JOptionPane.showMessageDialog(null, "Please fill in All the details");
                }

            }

        }
        Visibility(true);
        //getLastUniqueID();


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (lblMain.getText().equals("Login"))
        {
            if (comboType.getSelectedItem().toString().equals("Student")) 
            {
                if (txtUser.getText().length() == 0 || txtPassword.getText().length() == 0) 
                {
                    JOptionPane.showMessageDialog(null, "Please fill Both the details");
                } else
                {
                    LoginCall(txtUser.getText(), txtPassword.getText());
                    //txtUser.setText(null);
                    //txtPassword.setText(null);
                    //comboType.setSelectedItem(null);
                }
            }
            else if (comboType.getSelectedItem().toString().equals("Teacher")) 
            {
                
                if (txtUser.getText().length() == 0 || txtPassword.getText().length() == 0) 
                {
                    JOptionPane.showMessageDialog(null, "Please fill Both the details");
                } else
                {
                    LoginCallTeacher(txtUser.getText(), txtPassword.getText());
                    //txtUser.setText(null);
                    //txtPassword.setText(null);
                    //comboType.setSelectedItem(null);
                }
            }
        }
        Visibility(false);


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtUser.setText("");
        txtPassword.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        comboType.setSelectedItem("");


    }//GEN-LAST:event_btnClearActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
       if(comboType.getSelectedItem().toString().equals("Student"))
       {
           getLastUniqueIDStudent();
       }
       else
       {
           getLastUniqueIDTeacher();
       }
       
    }//GEN-LAST:event_comboTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    void Visibility(Boolean b) {
        lblName.setVisible(b);
        txtName.setVisible(b);
        lblPhone.setVisible(b);
        txtPhone.setVisible(b);
        lblEmail.setVisible(b);
        txtEmail.setVisible(b);
        txtUniqueID.setVisible(b);
        lblUniqueID.setVisible(b);

        if (b) {
            lblMain.setText("Register");
            btnLogin.setText("Already have an Account");
        } else {
            lblMain.setText("Login");
            btnLogin.setText("Login");
        }
    }

    //visibility method to hide the three label name, phone and email if user already have registered account
    /*void Visibility(Boolean b)
        {
                lblName.setVisible(b);
                txtName.setVisible(b);
                lblPhone.setVisible(b);
                txtPhone.setVisible(b);
                lblEmail.setVisible(b);
                txtEmail.setVisible(b);
                
                if(b)
                {
                    lblMain.setText("Register");
                    btnLogin.setText("Already have an account");
                    
                }
                else
                {
                    lblMain.setText("Login");
                    btnLogin.setText("Login");
                }

        }*/

    void LoginCall(String textUser, String txtPassword) {
        boolean flag = false;
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
            Statement stmnt = conn.createStatement();
            String qrry = "select * from student1 where username=\"" + textUser + "\"and password1=\"" + txtPassword + "\"";
            ResultSet rs = stmnt.executeQuery(qrry);
            while (rs.next()) {
                flag = true;
            }
            if (flag) {
                JOptionPane.showMessageDialog(null, "Sucessfully Logged in!");
                CanvasHomePage newHomePage = new CanvasHomePage();
                newHomePage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "User and password didn't match!");

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in connecting with mySql" + ex);
        }
    }

    void RegisterCall(String textUser, String txtPassword, String txtName, String txtEmail, String txtPhone, String uniqueID) {
        boolean flag = false;
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
            Statement stmnt = conn.createStatement();
            String qrry = "Insert into student1 VALUES ("
                    + "'" + textUser + "',"
                    + "'" + txtPassword + "',"
                    + "'" + txtName + "',"
                    + "'" + txtEmail + "',"
                    + "'" + txtPhone + "',"
                    + "'" + uniqueID + "'"
                    + ");";

            stmnt.executeUpdate(qrry);
            stmnt.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Great, You have sucessfully Registerd to Canvas!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in connecting with mySql" + ex);
        }

    }
     void RegisterCallTeacher(String textUser, String txtPassword, String txtName, String txtEmail, String txtPhone, String uniqueID) {
        boolean flag = false;
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
            Statement stmnt = conn.createStatement();
            String qrry = "Insert into teacher VALUES ("
                    + "'" + textUser + "',"
                    + "'" + txtPassword + "',"
                    + "'" + txtName + "',"
                    + "'" + txtEmail + "',"
                    + "'" + txtPhone + "',"
                    + "'" + uniqueID + "'"
                    + ");";

            stmnt.executeUpdate(qrry);
            stmnt.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Great, You have sucessfully Registerd to blackboard and considered a teacher of our campus!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in connecting with mySql" + ex);
        }

    }
     void LoginCallTeacher(String textUser, String txtPassword) {
        boolean flag = false;
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
            Statement stmnt = conn.createStatement();
            String qrry = "select * from teacher where username=\"" + textUser + "\"and password1=\"" + txtPassword + "\"";
            ResultSet rs = stmnt.executeQuery(qrry);
            while (rs.next()) {
                flag = true;
            }
            if (flag) {
                JOptionPane.showMessageDialog(null, "Sucessfully Logged in!");
                TeacherHomePage newHomePage = new TeacherHomePage();
                newHomePage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "User and password didn't match!");

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in connecting with mySql" + ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbluserType;
    private javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    public static javax.swing.JTextField txtUniqueID;
    public static javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
