/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

/**
 *
 * @author Bishal
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package LMS;

//import static LMS.ContentPageStudentCourse.lblCourseID;
//import static LMS.ContentPageStudentCourse.lblStudentID;
import Project1.ConnectionProvider;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Michelle
 */
public class SyllabusStudent extends javax.swing.JFrame {

    /**
     * Creates new form SyllabusStudent
     */
     //private String teacherID=IndividualCoursePageStudent.teacherID;
   // private String courseID=IndividualCoursePageStudent.courseID;
    private String studentID=IndividualCoursePageStudent.studentID;
    private ArrayList<String> studentIDAL = new ArrayList<String>();
    
    public SyllabusStudent() {
        initComponents();
        //getDetails();
        show_upload();
    }
    
    public SyllabusStudent(String studentID) {
        initComponents();
        show_upload();      
    }
    
    public ArrayList<Upload> UploadList() {
        ArrayList<Upload> uploadList = new ArrayList<>();
        try {
            String name="";
            String uniqueID="";
            
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/learningmanagementsystem", "root", "toor");
            Statement stmnt = conn.createStatement();
            ResultSet rs;
            rs = stmnt.executeQuery("select * from syllabus");
            
           // String qrry = "select * from syllabus";
            //Statement stmnt = conn.createStatement();
            //rs = stmnt.executeQuery(qrry);
            /*stmnt.executeUpdate(qrry);
            stmnt.close();
            conn.close();
             */
            Upload upload;
            while (rs.next()) {
                upload = new Upload(rs.getInt("id"), rs.getString("courseID"), rs.getString("teacherID"), rs.getString("assignmentName"), rs.getBytes("Image"), rs.getBytes("TxtFile"));
                uploadList.add(upload);
                
                name+=rs.getString(3);
                uniqueID+=rs.getString(6);
            }
            //lblCourseID.setText(name);
            //lblStudentID.setText(uniqueID);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
        return uploadList;
    }

    public void show_upload() {
        ArrayList<Upload> list = UploadList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Upload.getModel();
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            /*
            row[2] = list.get(i).getAssignmentName(); 
            row[0] = list.get(i).getCourseID();
            row[1] = list.get(i).getCourseName();
             */
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getAssignmentName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Upload = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        showTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Display_Upload.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Upload Name"
            }
        ));
        jTable_Display_Upload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UploadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Upload);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/Close all jframe.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Syllabus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addComponent(showTxt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        setVisible(false);
    }                                        

    private void jTable_Display_UploadMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        // TODO add your handling code here:
        int i = jTable_Display_Upload.getSelectedRow();
        TableModel model = jTable_Display_Upload.getModel();

        byte[] Pic = (UploadList().get(i).getPic());
        
        if(Pic != null){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(Pic).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH));
            image.setIcon(imageIcon);
        }
        else{
            image.setIcon(null);
        }
        
        byte[] Txt = (UploadList().get(i).getTxt());
        if(Txt != null){
            String s = new String(Txt);
            showTxt.setText(s);
        }
        else{
            showTxt.setText("");
        }
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SyllabusStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SyllabusStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SyllabusStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SyllabusStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SyllabusStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Upload;
    private javax.swing.JTextField showTxt;
    // End of variables declaration                   
}
